### ISSUE TITLE
Test is failed when rspec 3.8.0

### ISSUE THREAD

**Issue by sue445** [sue445/rubicure#176]
https://travis-ci.org/sue445/rubicure/builds/414397673

```
/home/travis/build/sue445/rubicure/vendor/bundle/ruby/2.5.0/gems/rspec-support-3.8.0/lib/rspec/support/object_formatter.rb:86: warning: wrong element type Rubicure::Girl at 0 (expected array)
/home/travis/build/sue445/rubicure/vendor/bundle/ruby/2.5.0/gems/rspec-support-3.8.0/lib/rspec/support/object_formatter.rb:86: warning: ignoring wrong elements is deprecated, remove them explicitly
/home/travis/build/sue445/rubicure/vendor/bundle/ruby/2.5.0/gems/rspec-support-3.8.0/lib/rspec/support/object_formatter.rb:86: warning: this causes ArgumentError in the next release


Failures:
  1) Rubicure::Core#each_with_series example at ./spec/rubicure/core_spec.rb:32 (Got an error when generating description from matcher: NoMethodError: undefined method `include?' for nil:NilClass -- /home/travis/build/sue445/rubicure/lib/rubicure/girl.rb:285:in `respond_to_missing?')
     Failure/Error: transform_calls.include?(shortened_name)
     
     NoMethodError:
       undefined method `include?' for nil:NilClass
     # ./lib/rubicure/girl.rb:285:in `respond_to_missing?'
     # ./vendor/bundle/ruby/2.5.0/gems/hashie-3.5.7/lib/hashie/extensions/method_access.rb:32:in `respond_to?'
     # ./vendor/bundle/ruby/2.5.0/gems/hashie-3.5.7/lib/hashie/extensions/method_access.rb:32:in `respond_to?'
     # ./vendor/bundle/ruby/2.5.0/gems/hashie-3.5.7/lib/hashie/extensions/method_access.rb:72:in `respond_to?'
     # ./vendor/bundle/ruby/2.5.0/gems/hashie-3.5.7/lib/hashie/extensions/method_access.rb:113:in `respond_to?'
     # ./lib/rubicure/series.rb:62:in `each'
     # ./lib/rubicure/series.rb:62:in `each'
     # ./lib/rubicure/core.rb:207:in `block in each_with_series'
     # ./lib/rubicure/core.rb:205:in `each'
     # ./lib/rubicure/core.rb:205:in `each_with_series'
     # ./spec/rubicure/core_spec.rb:32:in `block (4 levels) in <top (required)>'
     # ./spec/rubicure/core_spec.rb:32:in `block (3 levels) in <top (required)>'
```
